# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.reliancenetwork.com:
  peer0.infrastructure.reliancenetwork.com:
  peer1.infrastructure.reliancenetwork.com:
  peer0.power.reliancenetwork.com:
  peer1.power.reliancenetwork.com:
  peer0.communications.reliancenetwork.com:
  peer1.communications.reliancenetwork.com:
  peer0.entertainment.reliancenetwork.com:
  peer1.entertainment.reliancenetwork.com:
  peer0.capital.reliancenetwork.com:
  peer1.capital.reliancenetwork.com:

networks:
  byfn:

services:

  orderer.reliancenetwork.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.reliancenetwork.com
    container_name: orderer.reliancenetwork.com
    networks:
      - byfn

  peer0.infrastructure.reliancenetwork.com:
    container_name: peer0.infrastructure.reliancenetwork.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.infrastructure.reliancenetwork.com
    networks:
      - byfn

  peer1.infrastructure.reliancenetwork.com:
    container_name: peer1.infrastructure.reliancenetwork.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.infrastructure.reliancenetwork.com
    networks:
      - byfn

  peer0.power.reliancenetwork.com:
    container_name: peer0.power.reliancenetwork.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.power.reliancenetwork.com
    networks:
      - byfn

  peer1.power.reliancenetwork.com:
    container_name: peer1.power.reliancenetwork.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.power.reliancenetwork.com
    networks:
      - byfn

  peer0.communications.reliancenetwork.com:
    container_name: peer0.communications.reliancenetwork.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.communications.reliancenetwork.com
    networks:
      - byfn

  peer1.communications.reliancenetwork.com:
    container_name: peer1.communications.reliancenetwork.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.communications.reliancenetwork.com
    networks:
      - byfn

  peer0.entertainment.reliancenetwork.com:
    container_name: peer0.entertainment.reliancenetwork.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.entertainment.reliancenetwork.com
    networks:
      - byfn

  peer1.entertainment.reliancenetwork.com:
    container_name: peer1.entertainment.reliancenetwork.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.entertainment.reliancenetwork.com
    networks:
      - byfn

  peer0.capital.reliancenetwork.com:
    container_name: peer0.capital.reliancenetwork.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.capital.reliancenetwork.com
    networks:
      - byfn

  peer1.capital.reliancenetwork.com:
    container_name: peer1.capital.reliancenetwork.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.capital.reliancenetwork.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.infrastructure.reliancenetwork.com:7051
      - CORE_PEER_LOCALMSPID=InfrastructureMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/infrastructure.reliancenetwork.com/peers/peer0.infrastructure.reliancenetwork.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/infrastructure.reliancenetwork.com/peers/peer0.infrastructure.reliancenetwork.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/infrastructure.reliancenetwork.com/peers/peer0.infrastructure.reliancenetwork.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/infrastructure.reliancenetwork.com/users/Admin@infrastructure.reliancenetwork.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.reliancenetwork.com
      - peer0.infrastructure.reliancenetwork.com
      - peer1.infrastructure.reliancenetwork.com
      - peer0.power.reliancenetwork.com
      - peer1.power.reliancenetwork.com
      - peer0.communications.reliancenetwork.com
      - peer1.communications.reliancenetwork.com
      - peer0.entertainment.reliancenetwork.com
      - peer1.entertainment.reliancenetwork.com
      - peer0.capital.reliancenetwork.com
      - peer1.capital.reliancenetwork.com
    networks:
      - byfn
